// SPDX-License-Identifier: MIT
// Copyright (C) 2026 Signalroute

//go:build ignore
// +build ignore

// gen_gsm7.go generates gsm7_table.go from the 3GPP TS 23.038 basic character
// set definition. Run via:
//
//	go generate ./internal/at/...
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
)

// 3GPP TS 23.038 Table 6.2.1 — GSM 7-bit Default Alphabet
var gsm7Basic = [128]rune{
	'@', '£', '$', '¥', 'è', 'é', 'ù', 'ì', 'ò', 'Ç', '\n', 'Ø', 'ø', '\r', 'Å', 'å',
	'Δ', '_', 'Φ', 'Γ', 'Λ', 'Ω', 'Π', 'Ψ', 'Σ', 'Θ', 'Ξ', 0x1B, 'Æ', 'æ', 'ß', 'É',
	' ', '!', '"', '#', '¤', '%', '&', '\'', '(', ')', '*', '+', ',', '-', '.', '/',
	'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '=', '>', '?',
	'¡', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O',
	'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'Ä', 'Ö', 'Ñ', 'Ü', '§',
	'¿', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o',
	'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'ä', 'ö', 'ñ', 'ü', 'à',
}

// 3GPP TS 23.038 Table 6.2.1.1 — GSM 7-bit Default Extension Table
var gsm7Extension = map[byte]rune{
	0x0A: '\f',
	0x14: '^',
	0x28: '{',
	0x29: '}',
	0x2F: '\\',
	0x3C: '[',
	0x3D: '~',
	0x3E: ']',
	0x40: '|',
	0x65: '€',
}

func main() {
	var buf bytes.Buffer

	fmt.Fprintln(&buf, "// Code generated by gen_gsm7.go; DO NOT EDIT.")
	fmt.Fprintln(&buf, "// Source: 3GPP TS 23.038 Table 6.2.1 and Table 6.2.1.1")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "package at")
	fmt.Fprintln(&buf)

	// Basic charset.
	fmt.Fprintln(&buf, "// gsm7Charset maps GSM7 code point (0-127) to Unicode rune.")
	fmt.Fprintln(&buf, "// 3GPP TS 23.038 Table 6.2.1 — GSM 7-bit Default Alphabet.")
	fmt.Fprintln(&buf, "var gsm7Charset = [128]rune{")
	for i := 0; i < 128; i += 16 {
		fmt.Fprint(&buf, "\t")
		for j := i; j < i+16; j++ {
			r := gsm7Basic[j]
			if j > i {
				fmt.Fprint(&buf, " ")
			}
			switch {
			case r == '\n':
				fmt.Fprint(&buf, "'\\n',")
			case r == '\r':
				fmt.Fprint(&buf, "'\\r',")
			case r == '\'':
				fmt.Fprint(&buf, "0x27,")
			case r == 0x1B:
				fmt.Fprint(&buf, "0x1B,")
			case r >= 0x20 && r <= 0x7E:
				fmt.Fprintf(&buf, "'%c',", r)
			default:
				fmt.Fprintf(&buf, "'\\u%04x',", r)
			}
		}
		fmt.Fprintln(&buf)
	}
	fmt.Fprintln(&buf, "}")
	fmt.Fprintln(&buf)

	// Extension charset.
	fmt.Fprintln(&buf, "// gsm7Extension maps GSM7 extension-table code points to Unicode rune.")
	fmt.Fprintln(&buf, "// 3GPP TS 23.038 Table 6.2.1.1 — GSM 7-bit Default Extension Table.")
	fmt.Fprintln(&buf, "var gsm7Extension = map[byte]rune{")
	for _, code := range []byte{0x0A, 0x14, 0x28, 0x29, 0x2F, 0x3C, 0x3D, 0x3E, 0x40, 0x65} {
		r := gsm7Extension[code]
		switch {
		case r == '\f':
			fmt.Fprintf(&buf, "\t0x%02X: '\\f',\n", code)
		case r == '\\':
			fmt.Fprintf(&buf, "\t0x%02X: '\\\\',\n", code)
		default:
			fmt.Fprintf(&buf, "\t0x%02X: '%c',\n", code, r)
		}
	}
	fmt.Fprintln(&buf, "}")
	fmt.Fprintln(&buf)

	// Reverse lookup.
	fmt.Fprintln(&buf, "// gsm7Reverse maps Unicode rune to GSM7 basic code point.")
	fmt.Fprintln(&buf, "var gsm7Reverse = map[rune]byte{")
	for i, r := range gsm7Basic {
		if r == 0x1B || r == 0 {
			continue
		}
		switch {
		case r == '\n':
			fmt.Fprintf(&buf, "\t'\\n': 0x%02X,\n", i)
		case r == '\r':
			fmt.Fprintf(&buf, "\t'\\r': 0x%02X,\n", i)
		case r == '\'':
			fmt.Fprintf(&buf, "\t0x%04X: 0x%02X,\n", r, i)
		case r >= 0x20 && r <= 0x7E:
			fmt.Fprintf(&buf, "\t'%c': 0x%02X,\n", r, i)
		default:
			fmt.Fprintf(&buf, "\t'\\u%04x': 0x%02X,\n", r, i)
		}
	}
	fmt.Fprintln(&buf, "}")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "gofmt: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile("gsm7_table.go", src, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("generated gsm7_table.go")
}
